---
couchbase-server:
  '5.5':
    release:  '5.5.6'
    stable:   '5.5.6'
  '6.0':
    release:  '6.0.5'
    stable:   '6.0.5'
  '6.5':
    release:  '6.5.2'
    stable:   '6.5.2'
  '6.6':
    release:  '6.6.5'
    stable:   '6.6.6-10576'
  '7.0':
    release:  '7.0.4'
    stable:   '7.0.4'
  '7.1':
    release:  '7.1.5'
    stable:   '7.1.6-3954'
  '7.2':
    release:  '7.2.4-7070'
    stable:   '7.2.5-7551'
  '7.5':
    stable:   '7.5.0-4670'
  '7.6':
    release:  '7.6.0-2176'
    stable:   '7.6.0-2176'
  '8.0':
    stable:   '8.0.0-1562'

# Other_products:
couchbase-operator:
  '1.2':
    release:  '1.2.2'
    stable:   '1.2.2'
  '2.0':
    release:  '2.0.1'
    stable:   '2.0.1'
# sync_gateway: etc
...
